elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
  replicas: 1
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi

service:
  enabled: true
  annotations: {}
  port: 9200
